mirros: Mirros
forum: Forum
wiki: Wiki
git: Git

services: Services

activities_records: Activities Records
no_activities: No Activities
more_activities: More Activites
recent_news: Recent News
no_news: No News
more_news: More News
